sudo: required
services:
  - docker

before_install:
  - docker build -t rajarz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rajarz/react-test npm test -- --coverage

after_success:
  - docker build -t rajarz/multi-client ./client
  - docker build -t rajarz/multi-nginx ./nginx
  - docker build -t rajarz/multi-server ./server
  - docker build -t rajarz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rajarz/multi-client
  - docker push rajarz/multi-nginx
  - docker push rajarz/multi-server
  - docker push rajarz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-089956021384
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
